AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PeerSupportTesting:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          SECRET_ENV: <YOUR_SECRET_NAME>  # e.g., peer-support-prod-config
          AWS_REGION: !Ref AWS::Region
      # AutoPublishAlias: live
      # DeploymentPreference:
      #   Type: Linear10PercentEvery1Minute
      #   Alarms:
      #     - AliasErrorMetricGreaterThanZeroAlarm
      Policies:
        - DynamoDBReadPolicy:
            TableName: <YOUR_DYNAMODB_TABLE>  # e.g., PeerSupportTestTable
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ServerlessRestApi
            Stage: !Ref ServerlessRestApiProdStage
      AutoPublishAlias: live

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda function errors
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Dimensions:
        - Name: FunctionName
          Value: !Ref PeerSupportTesting
        - Name: Resource
          Value: !Sub "${PeerSupportTesting}:live"